"""add column 'reasons'

Revision ID: fe200a4ce74d
Revises: 20260529_0001
Create Date: 2026-05-30 10:31:15.116383+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'fe200a4ce74d'
down_revision: Union[str, Sequence[str], None] = '20260529_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('reasons', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'reasons')
    # ### end Alembic commands ###
