from __future__ import annotations

import json
from dataclasses import dataclass

import joblib
import numpy as np
import pandas as pd

from fraud_stream.config import ARTIFACTS_DIR


REASON_TEMPLATES = {
    "TX_AMOUNT": "Сумма транзакции влияет на повышение риска",
    "amount_ratio_to_customer_avg_7d": "Сумма выше обычного поведения клиента за последние 7 дней",
    "amount_zscore_customer": "Сумма нетипична относительно истории клиента",
    "customer_nb_tx_1d": "Количество операций клиента за последние сутки нетипично",
    "customer_nb_tx_7d": "Частота операций клиента за последние 7 дней повышает риск",
    "customer_sum_amount_1d": "Суммарный объем операций за сутки повышает риск",
    "terminal_risk_7d_delay7": "У терминала повышенный исторический fraud-risk",
    "terminal_risk_30d_delay7": "У терминала повышенный долгосрочный fraud-risk",
    "is_night": "Операция совершена в ночное время",
    "is_weekend": "Операция совершена в выходной день",
    "distance_customer_terminal": "Терминал находится далеко от типичной зоны клиента",
}


def _get_transformed_feature_names(pipeline) -> list[str]:
    preprocessor = pipeline.named_steps["preprocessor"]
    names = []
    try:
        names = list(preprocessor.get_feature_names_out())
    except Exception:
        names = []
    # Clean prefixes: num__TX_AMOUNT -> TX_AMOUNT; cat__CUSTOMER_ID_123 -> CUSTOMER_ID_123
    return [n.split("__", 1)[-1] for n in names]


def explain_with_shap(X_sample: pd.DataFrame, max_rows: int = 200):
    """Create SHAP values for the best supervised model.

    For tree models with preprocessing pipeline, this explains transformed features.
    If SHAP fails for a model, it falls back to no-op and lets reason-code logic still work.
    """
    import shap

    pipeline = joblib.load(ARTIFACTS_DIR / "best_supervised_pipeline.joblib")
    X = X_sample.head(max_rows).copy()

    Xt = pipeline.named_steps["preprocessor"].transform(X)
    model = pipeline.named_steps["model"]

    feature_names = _get_transformed_feature_names(pipeline)
    if not feature_names or len(feature_names) != Xt.shape[1]:
        feature_names = [f"f_{i}" for i in range(Xt.shape[1])]

    try:
        explainer = shap.TreeExplainer(model)
        values = explainer.shap_values(Xt)
        if isinstance(values, list):
            values = values[1]
        shap_df = pd.DataFrame(values, columns=feature_names)
    except Exception:
        explainer = shap.Explainer(model.predict_proba, Xt)
        values = explainer(Xt)
        arr = values.values
        if arr.ndim == 3:
            arr = arr[:, :, 1]
        shap_df = pd.DataFrame(arr, columns=feature_names)

    shap_df.to_parquet(ARTIFACTS_DIR / "shap_values_sample.parquet", index=False)
    return shap_df


def simple_reason_codes(row: pd.Series, top_k: int = 5) -> list[str]:
    """Rule-assisted reason codes.

    This is intentionally not pure SHAP: in production, analyst-readable reasons are
    often generated by combining model explanations with domain templates.
    """
    candidates = []

    def add(condition, key, strength):
        if condition:
            candidates.append((strength, REASON_TEMPLATES.get(key, key)))

    add(row.get("amount_ratio_to_customer_avg_7d", 0) > 2.0, "amount_ratio_to_customer_avg_7d", row.get("amount_ratio_to_customer_avg_7d", 0))
    add(abs(row.get("amount_zscore_customer", 0)) > 3.0, "amount_zscore_customer", abs(row.get("amount_zscore_customer", 0)))
    add(row.get("customer_nb_tx_1d", 0) > 5, "customer_nb_tx_1d", row.get("customer_nb_tx_1d", 0))
    add(row.get("customer_sum_amount_1d", 0) > 500, "customer_sum_amount_1d", row.get("customer_sum_amount_1d", 0) / 100)
    add(row.get("terminal_risk_7d_delay7", 0) > 0.05, "terminal_risk_7d_delay7", row.get("terminal_risk_7d_delay7", 0) * 100)
    add(row.get("is_night", 0) == 1, "is_night", 1)
    add(row.get("is_weekend", 0) == 1, "is_weekend", 0.5)
    add(row.get("distance_customer_terminal", 0) > 10, "distance_customer_terminal", row.get("distance_customer_terminal", 0) / 10)

    if not candidates:
        return ["Риск сформирован совокупностью слабых факторов без одного доминирующего признака"]

    candidates = sorted(candidates, key=lambda x: x[0], reverse=True)
    return [reason for _, reason in candidates[:top_k]]
